<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Bus Client that is API compatible with 1.x.</Description>
    <AssemblyTitle>RawRabbit.Compatibility.Legacy</AssemblyTitle>
    <Version>2.0.0-alpha</Version>
    <Authors>pardahlman</Authors>
    <AssemblyName>RawRabbit.Compatibility.Legacy</AssemblyName>
    <PackageId>RawRabbit.Compatibility.Legacy</PackageId>
    <PackageTags>rabbitmq;rawrabbit;compatibility</PackageTags>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RawRabbit.Operations.Request\RawRabbit.Operations.Request.csproj" />
    <ProjectReference Include="..\RawRabbit.Operations.Publish\RawRabbit.Operations.Publish.csproj" />
    <ProjectReference Include="..\RawRabbit.Enrichers.MessageContext.Respond\RawRabbit.Enrichers.MessageContext.Respond.csproj" />
    <ProjectReference Include="..\RawRabbit.Enrichers.MessageContext\RawRabbit.Enrichers.MessageContext.csproj" />
    <ProjectReference Include="..\RawRabbit.Enrichers.MessageContext.Subscribe\RawRabbit.Enrichers.MessageContext.Subscribe.csproj" />
  </ItemGroup>

</Project>
