<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Enricher RawRabbit with a Retry Later capabilities</Description>
    <AssemblyTitle>RawRabbit.Enrichers.RetryLater</AssemblyTitle>
    <VersionPrefix>2.0.0</VersionPrefix>
    <Authors>pardahlman</Authors>
    <AssemblyName>RawRabbit.Enrichers.RetryLater</AssemblyName>
    <PackageId>RawRabbit.Enrichers.RetryLater</PackageId>
    <PackageTags>rabbitmq;rawrabbit;enrichers;retry-later</PackageTags>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <RootNamespace>RawRabbit</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RawRabbit\RawRabbit.csproj" />
  </ItemGroup>

</Project>
