<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Enrich the BusClient with SubscribeAsync, used for message consume.</Description>
    <AssemblyTitle>RawRabbit.Operations.Subscribe</AssemblyTitle>
    <VersionPrefix>2.0.0</VersionPrefix>
    <Authors>pardahlman;enrique-avalon</Authors>
    <AssemblyName>RawRabbit.Operations.Subscribe</AssemblyName>
    <PackageId>RawRabbit.Operations.Subscribe</PackageId>
    <PackageTags>rabbitmq;rawrabbit;operation;subscribe</PackageTags>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <RepositoryUrl>https://github.com/pardahlman/RawRabbit</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RawRabbit\RawRabbit.csproj" />
  </ItemGroup>

</Project>
