<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Message headers and routing with Global Execution Id</Description>
    <AssemblyTitle>RawRabbit.Enrichers.GlobalExecutionId</AssemblyTitle>
    <VersionPrefix>2.0.0</VersionPrefix>
    <Authors>pardahlman</Authors>
    <AssemblyName>RawRabbit.Enrichers.GlobalExecutionId</AssemblyName>
    <PackageId>RawRabbit.Enrichers.GlobalExecutionId</PackageId>
    <PackageTags>rabbitmq;rawrabbit;global;executionid</PackageTags>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RawRabbit\RawRabbit.csproj" />
  </ItemGroup>

</Project>
