<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Enrich the BusClient with PublishAsync, used to perform a BasicPublish</Description>
    <AssemblyTitle>RawRabbit.Operations.Publish</AssemblyTitle>
    <VersionPrefix>2.0.0</VersionPrefix>
    <Authors>pardahlman;enrique-avalon</Authors>
    <AssemblyName>RawRabbit.Operations.Publish</AssemblyName>
    <PackageId>RawRabbit.Operations.Publish</PackageId>
    <PackageTags>rabbitmq;rawrabbit;operation;publish</PackageTags>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RawRabbit\RawRabbit.csproj" />
  </ItemGroup>

</Project>
