<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>A modern framework for communication over RabbitMq.</Description>
    <AssemblyTitle>RawRabbit</AssemblyTitle>
    <VersionPrefix>2.0.0</VersionPrefix>
    <Authors>pardahlman;enrique-avalon</Authors>
    <AssemblyName>RawRabbit</AssemblyName>
    <PackageId>RawRabbit</PackageId>
    <PackageTags>rabbitmq;rawrabbit;amqp</PackageTags>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <DefineConstants>$(DefineConstants);LIBLOG_PORTABLE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

</Project>
