<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Route messages based on Routing Attributes. Includes attributes for Exchange, Queue and Routing.</Description>
    <AssemblyTitle>RawRabbit.Enrichers.Attributes</AssemblyTitle>
    <VersionPrefix>2.0.0</VersionPrefix>
    <Authors>pardahlman</Authors>
    <AssemblyName>RawRabbit.Enrichers.Attributes</AssemblyName>
    <PackageId>RawRabbit.Enrichers.Attributes</PackageId>
    <PackageTags>rabbitmq;rawrabbit;attributes</PackageTags>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RawRabbit\RawRabbit.csproj" />
  </ItemGroup>

</Project>
