<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Exception handling and retry policies with Polly.</Description>
    <AssemblyTitle>RawRabbit.Enrichers.Polly</AssemblyTitle>
    <VersionPrefix>2.0.0</VersionPrefix>
    <Authors>pardahlman</Authors>
    <AssemblyName>RawRabbit.Enrichers.Polly</AssemblyName>
    <PackageId>RawRabbit.Enrichers.Polly</PackageId>
    <PackageTags>rabbitmq;rawrabbit;policy;polly</PackageTags>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RawRabbit\RawRabbit.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Polly" />
  </ItemGroup>

</Project>
