<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Suffix the Queue Name with application name, host name or a string of your choice.</Description>
    <AssemblyTitle>RawRabbit.Enrichers.QueueSuffix</AssemblyTitle>
    <VersionPrefix>2.0.0</VersionPrefix>
    <Authors>pardahlman</Authors>
    <AssemblyName>RawRabbit.Enrichers.QueueSuffix</AssemblyName>
    <PackageId>RawRabbit.Enrichers.QueueSuffix</PackageId>
    <PackageTags>rabbitmq;rawrabbit;queuesuffix</PackageTags>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RawRabbit\RawRabbit.csproj" />
  </ItemGroup>

</Project>
