<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Enrich the BusClient with GetAsync, that leverages BasicGet (the 'pull-API')</Description>
    <AssemblyTitle>RawRabbit.Operations.Get</AssemblyTitle>
    <VersionPrefix>2.0.0</VersionPrefix>
    <Authors>pardahlman;enrique-avalon</Authors>
    <AssemblyName>RawRabbit.Operations.Get</AssemblyName>
    <PackageId>RawRabbit.Operations.Get</PackageId>
    <PackageTags>rabbitmq;rawrabbit;operation;get</PackageTags>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RawRabbit.Operations.Tools\RawRabbit.Operations.Tools.csproj" />
    <ProjectReference Include="..\RawRabbit\RawRabbit.csproj" />
  </ItemGroup>

</Project>
