<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Enrich the BusClient with a Respond method that has argument for Message Context.</Description>
    <AssemblyTitle>RawRabbit.Enrichers.MessageContext.Respond</AssemblyTitle>
    <VersionPrefix>2.0.0</VersionPrefix>
    <Authors>pardahlman</Authors>
    <AssemblyName>RawRabbit.Enrichers.MessageContext.Respond</AssemblyName>
    <PackageId>RawRabbit.Enrichers.MessageContext.Respond</PackageId>
    <PackageTags>rabbitmq;rawrabbit;respond;operation;messagecontext</PackageTags>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RawRabbit.Operations.Respond\RawRabbit.Operations.Respond.csproj" />
  </ItemGroup>

</Project>
