<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Enrich the IPipeContext with current HttpContext</Description>
    <AssemblyTitle>RawRabbit.Enrichers.HttpContext</AssemblyTitle>
    <VersionPrefix>2.0.0</VersionPrefix>
    <Authors>pardahlman</Authors>
    <AssemblyName>RawRabbit.Enrichers.HttpContext</AssemblyName>
    <PackageId>RawRabbit.Enrichers.HttpContext</PackageId>
    <PackageTags>rabbitmq;rawrabbit;httpcontext</PackageTags>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RawRabbit\RawRabbit.csproj" />
  </ItemGroup>

</Project>
