<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <AssemblyName>RawRabbit.Messages.Sample</AssemblyName>
    <PackageId>RawRabbit.Messages.Sample</PackageId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RawRabbit.Enrichers.Attributes\RawRabbit.Enrichers.Attributes.csproj" />
  </ItemGroup>

</Project>
