<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>LordMike</Authors>
    <AssemblyTitle>RawRabbit.Enrichers.MessagePack</AssemblyTitle>
    <VersionPrefix>2.0.0</VersionPrefix>
    <PackageId>RawRabbit.Enrichers.MessagePack</PackageId>
    <PackageTags>rabbitmq;rawrabbit;messagepack</PackageTags>
    <Description>Serialize messages with MessagePack in RawRabbit</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="1.7.3.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RawRabbit\RawRabbit.csproj" />
  </ItemGroup>

</Project>
